# Generated by Django 4.1.5 on 2023-01-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorturl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('surl', models.CharField(max_length=128)),
                ('data', models.DateTimeField()),
                ('created_user', models.CharField(max_length=64)),
            ],
        ),
    ]
