# Generated by Django 4.1.5 on 2023-01-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='data',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='created_user',
            field=models.CharField(default='someone', max_length=64),
        ),
    ]
