# Generated by Django 4.1.5 on 2023-01-20 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xrapi', '0002_remove_shorturl_data_alter_shorturl_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=64),
        ),
    ]
