# Generated by Django 4.1.5 on 2023-01-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrapi', '0003_shorturl_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, verbose_name='邀请码')),
                ('timeslimit', models.IntegerField(default=1, verbose_name='限制次数')),
                ('created_user', models.CharField(max_length=64)),
            ],
        ),
    ]
