# Generated by Django 4.1.5 on 2023-01-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrapi', '0004_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation_code',
            name='timeslimit',
            field=models.IntegerField(default=0, verbose_name='已使用次数'),
        ),
    ]
