# Generated by Django 4.1.5 on 2023-01-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrapi', '0005_alter_invitation_code_timeslimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_code',
            name='timesused',
            field=models.IntegerField(default=0, verbose_name='已使用次数'),
        ),
        migrations.AlterField(
            model_name='invitation_code',
            name='timeslimit',
            field=models.IntegerField(default=1, verbose_name='限制次数'),
        ),
    ]
