# Generated by Django 4.1.5 on 2023-01-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xrapi', '0006_invitation_code_timesused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='click_times',
            field=models.IntegerField(default=0, max_length=1024, verbose_name='访问次数'),
        ),
    ]
